#pragma once
#include "sdkconfig.h"
#define RADIO_I2S_BCLK     CONFIG_RADIO_I2S_BCLK_GPIO
#define RADIO_I2S_WS       CONFIG_RADIO_I2S_WS_GPIO
#define RADIO_I2S_DOUT     CONFIG_RADIO_I2S_DOUT_GPIO
#define RADIO_I2S_ENABLE   CONFIG_RADIO_I2S_ENABLE_GPIO

